# Numpy Tutorial

## 1. Basics of Numpy

In [1]:
import numpy as np

In [2]:
print("Hello World!!!")

Hello World!!!


In [3]:
myArray1 = np.array([1,2,3,4,5,6], np.int8)

In [4]:
myArray1

array([1, 2, 3, 4, 5, 6], dtype=int8)

In [5]:
myArray1.shape

(6,)

In [6]:
myArray2 = np.array([[12019002004003,12019002004004]],np.int64)

In [7]:
myArray2

array([[12019002004003, 12019002004004]], dtype=int64)

In [8]:
myArray2.shape

(1, 2)

In [9]:
myArray2.dtype

dtype('int64')

## 2. Array Creation

In [10]:
listArray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [11]:
listArray.shape

(3, 3)

In [12]:
zeros = np.zeros((2,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
rng = np.arange(1, 15)
print(rng)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [14]:
lspace = np.linspace(1,10,100)
print(lspace)

[ 1.          1.09090909  1.18181818  1.27272727  1.36363636  1.45454545
  1.54545455  1.63636364  1.72727273  1.81818182  1.90909091  2.
  2.09090909  2.18181818  2.27272727  2.36363636  2.45454545  2.54545455
  2.63636364  2.72727273  2.81818182  2.90909091  3.          3.09090909
  3.18181818  3.27272727  3.36363636  3.45454545  3.54545455  3.63636364
  3.72727273  3.81818182  3.90909091  4.          4.09090909  4.18181818
  4.27272727  4.36363636  4.45454545  4.54545455  4.63636364  4.72727273
  4.81818182  4.90909091  5.          5.09090909  5.18181818  5.27272727
  5.36363636  5.45454545  5.54545455  5.63636364  5.72727273  5.81818182
  5.90909091  6.          6.09090909  6.18181818  6.27272727  6.36363636
  6.45454545  6.54545455  6.63636364  6.72727273  6.81818182  6.90909091
  7.          7.09090909  7.18181818  7.27272727  7.36363636  7.45454545
  7.54545455  7.63636364  7.72727273  7.81818182  7.90909091  8.
  8.09090909  8.18181818  8.27272727  8.36363636  8.45454545  8.545

In [16]:
emp = np.empty((2,6))
print(emp)

[[1.44678892e-311 2.47032823e-322 0.00000000e+000 0.00000000e+000
  1.89146896e-307 1.33664410e+160]
 [7.73565180e-091 1.31397851e-047 1.26138730e-076 5.24437449e+174
  3.99910963e+252 8.45603441e-307]]


In [17]:
idenditiy_matrix = np.identity(3)
print(idenditiy_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 3. Array Reshaping

In [18]:
myArr = np.arange(99)
myArr = myArr.reshape(3,33)
print(myArr)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56
  57 58 59 60 61 62 63 64 65]
 [66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89
  90 91 92 93 94 95 96 97 98]]


In [19]:
myArr = myArr.ravel()
print(myArr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98]


## 4. Numpy Axis

In [20]:
x = [[1,2,3], [4,5,6], [7,1,0]]

In [21]:
arr = np.array(x)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 1 0]]


In [22]:
axis0Sum = arr.sum(axis=0)

In [23]:
axis1Sum = arr.sum(axis=1)

In [25]:
print(axis0Sum,",",axis1Sum)

[12  8  9] , [ 6 15  8]


In [26]:
arr.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [27]:
for item in arr.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [28]:
arr.ndim

2

In [29]:
arr.size

9

In [31]:
arr.nbytes

36

In [34]:
oneDarray = np.empty((10))
print(oneDarray)

[1.44678892e-311 2.47032823e-322 1.89146896e-307 1.33664410e+160
 7.73565180e-091 1.31397851e-047 1.26138730e-076 5.24437449e+174
 3.99910963e+252 8.45603441e-307]


In [35]:
oneDarray.argmax()

8

In [36]:
oneDarray.argmin()

1

In [37]:
oneDarray.argsort()

array([1, 0, 2, 9, 4, 6, 5, 3, 7, 8], dtype=int64)

In [38]:
arr.argmax()

6

In [39]:
arr.argmin()

8

In [41]:
arr.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [42]:
arr.argmin(axis=0)

array([0, 2, 2], dtype=int64)

In [43]:
arr.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [44]:
arr.argmin(axis=1)

array([0, 0, 2], dtype=int64)

In [45]:
arr + arr

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14,  2,  0]])

In [46]:
arr * arr

array([[ 1,  4,  9],
       [16, 25, 36],
       [49,  1,  0]])

In [47]:
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [48]:
np.square(arr)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49,  1,  0]], dtype=int32)

In [49]:
np.sum(arr)

29

In [50]:
np.count_nonzero(arr)

8

In [51]:
arr.tolist()

[[1, 2, 3], [4, 5, 6], [7, 1, 0]]